loanMe/config/routes.rb
Rails.application.routes.draw do
  resources :friends
  get 'main_window/index'

root 'main_window#index'

  resources :item_loans
  resources :item_requests
  resources :items
  resources :users

  get 'items/:id/make_loan' => 'items#make_loan', as: :make_loan
  get 'item_requests/:id/make_loan' => 'item_requests#treat_request', as: :treat_request
  get 'friends/:id/friend_items' => 'friends#friend_items', as: :friend_items

  get 'users/:id/be_friends' => 'users#be_friends', as: :be_friends
  get 'users/:id/add_item' => 'users#add_item', as: :add_item
  get 'users/:id/see_items' => 'users#see_items', as: :see_items

end

loanMe/app/models/item.rb
class Item < ActiveRecord::Base
  validates :name, :description, presence: true
  belongs_to :user
  has_many :item_requests

  def loan
    self.update_attribute(:state, !self.state)
    self.save
  end




end

loanMe/app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :set_item, only: [:show, :edit, :update, :make_loan, :destroy]

  def make_loan
    @item.loan
    respond_to do |format|
        format.html {  redirect_to items_path, notice: 'Item was successfully updated.' }
      end
  end

  # GET /items
  # GET /items.json
  def index
    @items = Item.all
  end

  # GET /items/1
  # GET /items/1.json
  def show
  end

  # GET /items/new
  def new
    @item = Item.new
  end

  # GET /items/1/edit
  def edit
  end

  # POST /items
  # POST /items.json
  def create
    @item = Item.new(item_params)

    respond_to do |format|
      if @item.save
        format.html { redirect_to @item, notice: 'Item was successfully created.' }
        format.json { render :show, status: :created, location: @item }
      else
        format.html { render :new }
        format.json { render json: @item.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /items/1
  # PATCH/PUT /items/1.json
  def update
    respond_to do |format|
      if @item.update(item_params)
        format.html { redirect_to @item, notice: 'Item was successfully updated.' }
        format.json { render :show, status: :ok, location: @item }
      else
        format.html { render :edit }
        format.json { render json: @item.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /items/1
  # DELETE /items/1.json
  def destroy
    @item.destroy
    respond_to do |format|
      format.html { redirect_to items_url, notice: 'Item was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_item
      @item = Item.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def item_params
      params.require(:item).permit(:name, :description, :url, :state, :user_id)
    end
end

loanMe/app/helpers/items_helper.rb
module ItemsHelper
  def get_item_name_bu(user)
     @item = Item.find(:user_id, user.id)
     return @item.name
  end
end

loanMe/app/views/items/_form.html.erb
<%= form_for(@item) do |f| %>
  <% if @item.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@item.errors.count, "error") %> prohibited this item from being saved:</h2>

      <ul>
      <% @item.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>


  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_field :description %>
  </div>
  <div class="field">
    <%= f.label :url %><br>
    <%= f.text_field :url %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

loanMe/app/views/items/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Items</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th>Url</th>
      <th>State</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @items.each do |item| %>
      <tr>
        <td><%= item.name %></td>
        <td><%= item.description %></td>
        <td><%= link_to 'Link: ' + item.name, item.url %></td>
        <td><%= check_state(item) %></td>
        <td><%= link_to 'Show', item %></td>
        <td><%= link_to 'Edit', edit_item_path(item) %></td>
        <td><%= link_to 'Destroy', item, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <td><%= link_to 'Loan', make_loan_path(item)%></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Item', new_item_path %>
<p>
  <%= link_to 'Back', controller: 'main_window' %>
</p>

loanMe/app/views/items/show.html.erb
<p id="notice"><%= notice %></p>



<p>
  <strong>Name:</strong>
  <%= @item.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @item.description %>
</p>

<p>
  <strong>Url:</strong>
  <%= @item.url %>
</p>

<p>
  <strong>State:</strong>
  <%= if @item.state = true
    'Item in property'
  else
    'Item loaned'
  end %>
</p>

<%= link_to 'Edit', edit_item_path(@item) %> |
<%= link_to 'Back', items_path %>