loanMe2/config/routes.rb
Rails.application.routes.draw do

  get    'login'   => 'sessions#new'
  post   'login'   => 'sessions#create'
  delete 'logout'  => 'sessions#destroy'

  get 'main_window/index'
  root 'sessions#new'

  resources :items
  resources :users
  resources :item_loans
  resources :item_requests

  get 'users/:id/add_item' => 'users#add_item', as: :add_item
  get 'users/:id/see_items' => 'users#see_items', as: :see_items
  get 'users/:id/see_my_items' => 'users#see_my_items', as: :see_my_items

  get 'items/:id/request_item' => 'items#request_item', as: :request_item

  get 'item_requests/:id/loan_item' => 'item_requests#loan_item', as: :loan_item

  get 'item_loans/:id/item_return' => 'item_loans#item_return', as: :item_return

end

loanMe2/app/models/item.rb
class Item < ActiveRecord::Base
  belongs_to :user
  has_many :item_requests, dependent: :destroy

  def request
    @item_request = ItemRequest.new
    @item_request.user_id = self.user_id
    @item_request.item_id = self.id
    @item_request.save
  end

end

loanMe2/app/models/user.rb
class User < ActiveRecord::Base
  before_save { self.email = email.downcase }
  has_many :items, dependent: :destroy
  has_many :item_requests, dependent: :destroy
  validates :email, presence: true, uniqueness: { case_sensitive: false }
  has_secure_password
  validates :password, presence: true, length: { minimum: 6 }

  def request_item
    @item_request = ItemRequest.new
    @item_request.user_id = self.id
    @item_request.item_id = self.item.id
    @item_request.save
  end

  # Returns the hash digest of the given string.
  def User.digest(string)
    cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
                                                  BCrypt::Engine.cost
    BCrypt::Password.create(string, cost: cost)
  end

end

loanMe2/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  include SessionsHelper
end

loanMe2/app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :set_item, only: [:show, :edit, :update, :destroy, :request_item]


  def request_item
    @item.request
    respond_to do |format|
      format.html { redirect_to see_items_path(@item.user_id), notice: 'Item was successfully created.' }
    end
  end

  # GET /items
  # GET /items.json
  def index
    @items = Item.all.where.not(user_id: current_user.id)
  end

  # GET /items/1
  # GET /items/1.json
  def show
  end

  # GET /items/new
  def new
    @item = Item.new
  end

  # GET /items/1/edit
  def edit
  end

  # POST /items
  # POST /items.json
  def create
    @item = Item.new(item_params)

    respond_to do |format|
      if @item.save
        format.html { redirect_to current_user, notice: 'Item was successfully created.' }
        format.json { render :show, status: :created, location: @item }
      else
        format.html { render :new }
        format.json { render json: @item.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /items/1
  # PATCH/PUT /items/1.json
  def update
    respond_to do |format|
      if @item.update(item_params)
        format.html { redirect_to @item, notice: 'Item was successfully updated.' }
        format.json { render :show, status: :ok, location: @item }
      else
        format.html { render :edit }
        format.json { render json: @item.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /items/1
  # DELETE /items/1.json
  def destroy
    @item.destroy
    respond_to do |format|
      format.html { redirect_to see_my_items_path(current_user), notice: 'Item was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_item
      @item = Item.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def item_params
      params.require(:item).permit(:name, :description, :url, :state, :user_id)
    end
end

loanMe2/app/controllers/main_window_controller.rb
class MainWindowController < ApplicationController
  def index
  end
end

loanMe2/app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy, :add_item, :see_my_items,  :see_items, :request_item]



  def see_my_items
    @items = Item.where(user_id: current_user.id)
  end

  def see_items
    @items = Item.where(user_id: @user.id)
  end

  def add_item
    @item = Item.new
  end


  # GET /users
  # GET /users.json
  def index
    @users = User.all.where.not(id: current_user.id)
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)
    respond_to do |format|
      if @user.save
        log_in @user
        flash[:success] = "Welcome to the Sample App!"
        redirect_to @user
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:name, :surname, :email, :phonenumber, :password)
    end
end

loanMe2/app/helpers/application_helper.rb
module ApplicationHelper
end

loanMe2/app/helpers/items_helper.rb
module ItemsHelper

  def check_state(item)
     item.state ? 'Item in property' : 'Item loaned'
  end

  def request_item(item)
    @item_request = ItemRequest.new
    @item_request.user_id = item.user_id
    @item_request.item_id = item.id
    @item_request.save    
  end

end

loanMe2/app/helpers/main_window_helper.rb
module MainWindowHelper
end

loanMe2/app/helpers/users_helper.rb
module UsersHelper
end

loanMe2/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>LoanMe2</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<header>
  <%= render 'layouts/header' %>
</header>
<body>

<%= yield %>

</body>
</html>

loanMe2/app/views/main_window/index.html.erb
<h1>MainWindow index</h1>
<p>
  <%= link_to 'User', new_user_path%>
</p>
<p>
  <%= link_to 'Your items', controller: 'items'%>
</p>
<p>
  <%= link_to 'Item request', controller: 'item_requests'%>
</p>
<p>
  <%= link_to 'Item loan', controller: 'item_loans'%>
</p>

loanMe2/app/views/users/_form.html.erb
<div class="col-md-6 col-md-offset-3">
  <div class="container-fluid well">
    <div class="col-md-6 col-md-offset-3">
      <div class="container">
        <h1>Editing User</h1>
        <%= form_for(@user) do |f| %>
        <% if @user.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(@user.errors.count, "error") %>
            prohibited this user from being saved:</h2>

          <ul>
            <% @user.errors.full_messages.each do |message| %>
            <li><%= message %></li>
            <% end %>
          </ul>
        </div>
        <% end %>

        <div class="container">
          <div class="field">
            <%= f.label :name %><br>
            <%= f.text_field :name %>
          </div>
          <div class="field">
            <%= f.label :surname %><br>
            <%= f.text_field :surname %>
          </div>
          <div class="field">
            <%= f.label :email %><br>
            <%= f.text_field :email %>
          </div>
          <div class="field">
            <%= f.label :phonenumber %><br>
            <%= f.text_field :phonenumber %>
          </div>
          <div class="field">
            <%= f.label :password %><br>
            <%= f.text_field :password %>
          </div>
          <div class="container">
            <div class="col-md-6">
              <div class="actions">
                <%= f.submit "Update!", class:"btn btn-round" %>
              </div>
              <% end %>
              <%= link_to 'Back', current_user, class: "btn btn-round" %>
            </div>
          </div>
        </div>

      </div>
    </div>
  </div>
</div>

loanMe2/app/views/users/add_item.html.erb
<div class="col-md-6 col-md-offset-3">
  <div class="container-fluid well">
    <div class="col-md-6 col-md-offset-3">
      <h1>
        New Item
      </h1>
      <%= form_for(@item) do |f| %>
      <% if @item.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(@item.errors.count, "error") %>
          prohibited this item from being saved:
        </h2>
        <ul>
          <% @item.errors.full_messages.each do |message| %>
          <li><%= message %></li>
          <% end %>
        </ul>
      </div>
      <% end %>

      <%= f.hidden_field :user_id, value: @user.id%>
      <div class="field">
        <%= f.label :name %><br>
        <%= f.text_field :name %>
      </div>
      <div class="field">
        <%= f.label :description %><br>
        <%= f.text_field :description %>
      </div>
      <div class="field">
        <%= f.label :url %><br>
        <%= f.text_field :url %>
      </div>
      <div class="col-md-6">
        <div class="container">
          <div class="actions">
            <%= f.submit "Add Item", class: "btn btn-round" %>
            <p>
              <%= link_to 'Back', current_user, class: "btn btn-round" %>
            </p>
          </div>
        </div>
      </div>
      <% end %>
    </div>
  </div>
</div>

loanMe2/app/views/users/edit.html.erb
<%= render 'form' %>

loanMe2/app/views/users/index.html.erb
<!DOCTYPE html>
<div class="col-md-6 col-sm-offset-3">
  <div class="container">
    <div class="row">
      <div class="col-md-6">
        <div class="panel panel-primary">
          <div class="panel-heading">
            <h1 class="panel-title">
              Users
            </h1>
            <div class="pull-right">
              <form action="" class="search-form">
                <div class="form-group has-feedback">
                  <label class="sr-only" for="search">Search</label>
                  <input class="form-control" id="search" name="search" placeholder="search" type="text">
                  <span class="glyphicon glyphicon-search form-control-feedback"></span>
                </div>
              </form>
            </div>
          </div>
          <div class="panel-body">
            <input class="form-control" data-action="filter" data-filters="#dev-table" id="dev-table-filter" placeholder="Filter users" type="text" />
          </div>
          <table class="table table-hover" id="dev-table">
            <thead>
              <tr>
                <th>#</th>
                <th>Name</th>
                <th>Surname</th>
              </tr>
            </thead>
            <tbody>
              <% @users.each do |user| %>
                <tr>
                  <td>-</td>
                  <td>
                    <%= user.name %>
                  </td>
                  <td>
                    <%= user.surname %>
                  </td>
                  <td>
                    <%= link_to 'See items', see_items_path(user), class: "btn btn-round" %>
                  </td>
                </tr>
                <% end %>
            </tbody>
          </table>
        </div>
        <%= link_to 'Back to profile', current_user, class: "btn btn-round" %>
      </div>
    </div>
  </div>
</div>

loanMe2/app/views/users/new.html.erb
  <%= render 'form_new' %>

loanMe2/app/views/users/see_items.html.erb
<!DOCTYPE html>
<div class="col-md-6 col-sm-offset-3">
  <div class="container">
    <div class="row">
      <div class="col-md-6">
        <div class="panel panel-primary">
          <div class="panel-heading">
            <h1 class="panel-title">
              Items
            </h1>
          </div>
          <div class="panel-body">
            <input class="form-control" data-action="filter" data-filters="#dev-table" id="dev-table-filter" placeholder="Filter users" type="text" />
          </div>
          <table class="table table-hover" id="dev-table">
            <thead>
              <tr>
                <th>#</th>
                <th>Name</th>
                <th>Description</th>
                <th>State</th>
              </tr>
            </thead>
            <tbody>
              <% @items.each do |item| %>
                <tr>
                  <td>-</td>
                  <td>
                    <%= item.name %>
                  </td>
                  <td>
                    <%= item.description %>
                  </td>
                  <td>
                    <%= check_state(item) %>
                  </td>
                  <td>
                    <%= link_to 'Request item', request_item_path, class: "btn btn-round" %>
                  </td>
                </tr>
                <% end %>
            </tbody>
          </table>
        </div>
        <%= link_to 'Back to users', users_path, class: "btn btn-round" %>
      </div>
    </div>
  </div>
</div>

loanMe2/app/views/users/show.html.erb
<div class="col-md-7 col-md-offset-3">

  <br><br>
  <div class="container-fluid well span6 col-md-9">
    <div class="row-fluid">
      <!--div class="span2">
        <img class="img-circle" src="https://secure.gravatar.com/avatar/de9b11d0f9c0569ba917393ed5e5b3ab?s=140&r=g&d=mm">
      </div-->

      <div class="span8">
        <h1>
          <%= current_user.name%>
          <%= current_user.surname%>
        </h1>
        <h6>
          Email:
          <%= current_user.email%>
        </h6>
        <h6>
          Phonenumber:
          <%= current_user.phonenumber%>
        </h6>
        <h6>
          Password:
          <%= current_user.password%>
        </h6>
      </div>

      <div class="span2">
        <%= link_to 'Edit profile', edit_user_path, class: "btn btn-round" %>
        <%= link_to 'Add some items', add_item_path, class: "btn btn-round" %>
        <%= link_to 'See my items', see_my_items_path(current_user),  class: "btn btn-round" %>
        <%= link_to 'See users', users_path, class: "btn btn-round" %>
      </div>
    </div>
  </div>
</div>