loanMe/config/routes.rb
Rails.application.routes.draw do
  resources :friends
  get 'main_window/index'

root 'main_window#index'

  resources :item_loans
  resources :item_requests
  resources :items
  resources :users

  get 'items/:id/make_loan' => 'items#make_loan', as: :make_loan
  get 'item_requests/:id/make_loan' => 'item_requests#treat_request', as: :treat_request
  get 'friends/:id/friend_items' => 'friends#friend_items', as: :friend_items

  get 'users/:id/be_friends' => 'users#be_friends', as: :be_friends
  get 'users/:id/add_item' => 'users#add_item', as: :add_item
  get 'users/:id/see_items' => 'users#see_items', as: :see_items

end

loanMe/app/models/item_loan.rb
class ItemLoan < ActiveRecord::Base
  validates :item_id, :user_id, :estimated_return_date, presence: true
  has_one :item_requests
end

loanMe/app/controllers/item_loans_controller.rb
class ItemLoansController < ApplicationController
  before_action :set_item_loan, only: [:show, :edit, :update, :destroy]

  # GET /item_loans
  # GET /item_loans.json
  def index
    @item_loans = ItemLoan.all
  end

  # GET /item_loans/1
  # GET /item_loans/1.json
  def show
  end

  # GET /item_loans/new
  def new    
    @item_loan = ItemLoan.new
  end

  # GET /item_loans/1/edit
  def edit
  end

  # POST /item_loans
  # POST /item_loans.json
  def create
    @item_loan = ItemLoan.new(item_loan_params)

    respond_to do |format|
      if @item_loan.save
        format.html { redirect_to @item_loan, notice: 'Item loan was successfully created.' }
        format.json { render :show, status: :created, location: @item_loan }
      else
        format.html { render :new }
        format.json { render json: @item_loan.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /item_loans/1
  # PATCH/PUT /item_loans/1.json
  def update
    respond_to do |format|
      if @item_loan.update(item_loan_params)
        format.html { redirect_to @item_loan, notice: 'Item loan was successfully updated.' }
        format.json { render :show, status: :ok, location: @item_loan }
      else
        format.html { render :edit }
        format.json { render json: @item_loan.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /item_loans/1
  # DELETE /item_loans/1.json
  def destroy
    @item_loan.destroy
    respond_to do |format|
      format.html { redirect_to item_loans_url, notice: 'Item loan was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_item_loan
      @item_loan = ItemLoan.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def item_loan_params
      params.require(:item_loan).permit(:item_id, :user_id, :estimated_return_date)
    end
end

loanMe/app/helpers/item_loans_helper.rb
module ItemLoansHelper
end

loanMe/app/views/item_loans/_form.html.erb
<%= form_for(@item_loan) do |f| %>
  <% if @item_loan.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@item_loan.errors.count, "error") %> prohibited this item_loan from being saved:</h2>

      <ul>
      <% @item_loan.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :item_id %><br>
    <%= f.text_field :item_id %>
  </div>
  <div class="field">
    <%= f.label :user_id %><br>
    <%= f.text_field :user_id %>
  </div>
  <div class="field">
    <%= f.label :estimated_return_date %><br>
    <%= f.text_field :estimated_return_date %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

loanMe/app/views/item_loans/edit.html.erb
<h1>Editing Item Loan</h1>

<%= render 'form' %>

<%= link_to 'Show', @item_loan %> |
<%= link_to 'Back', item_loans_path %>

loanMe/app/views/item_loans/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Item Loans</h1>

<table>
  <thead>
    <tr>
      <th>Item</th>
      <th>User</th>
      <th>Item state</th>
      <th>Estimated return date</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @item_loans.each do |item_loan| %>
      <tr>
        <td><%= item_loan.item_id %></td>
        <td><%= item_loan.user_id %></td>
        <td><%= item_loan.estimated_return_date %></td>
        
        <td><%= link_to 'Show', item_loan %></td>
        <td><%= link_to 'Destroy', item_loan, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<p>
  <%= link_to 'Back', controller: 'main_window' %>
</p>

loanMe/app/views/item_loans/new.html.erb
<h1>New Item Loan</h1>

<%= render 'form' %>

<%= link_to 'Back', item_loans_path %>

loanMe/app/views/item_loans/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Item:</strong>
  <%= @item_loan.item_id %>
</p>

<p>
  <strong>User:</strong>
  <%= @item_loan.user_id %>
</p>

<p>
  <strong>Estimated return date:</strong>
  <%= @item_loan.estimated_return_date %>
</p>

<%= link_to 'Edit', edit_item_loan_path(@item_loan) %> |
<%= link_to 'Back', item_loans_path %>