loanMe/config/routes.rb
Rails.application.routes.draw do
  resources :friends
  get 'main_window/index'

root 'main_window#index'

  resources :item_loans
  resources :item_requests
  resources :items
  resources :users

  get 'items/:id/make_loan' => 'items#make_loan', as: :make_loan
  get 'item_requests/:id/make_loan' => 'item_requests#treat_request', as: :treat_request
  get 'friends/:id/friend_items' => 'friends#friend_items', as: :friend_items

  get 'users/:id/be_friends' => 'users#be_friends', as: :be_friends
  get 'users/:id/add_item' => 'users#add_item', as: :add_item
  get 'users/:id/see_items' => 'users#see_items', as: :see_items

end

loanMe/app/models/item_request.rb
class ItemRequest < ActiveRecord::Base
  validates :user_id, :item_id, :date_request, :estimated_return_date, presence: true
  belongs_to :user
  belongs_to :item

  def loan
    @item_loan = ItemLoan.new
    @item_loan.item_id = self.item_id
    @item_loan.user_id = self.user_id
    @item_loan.estimated_return_date = self.estimated_return_date
    @item_loan.save
  end


end

loanMe/app/controllers/item_requests_controller.rb
class ItemRequestsController < ApplicationController
  before_action :set_item_request, only: [:show, :edit, :update, :treat_request, :destroy]

  def treat_request
    @item_request.loan
    redirect_to do |format|
      format.html { redirect_to item_requests_url, notice: 'Item request was successfully created.' }
    end
  end


  # GET /item_requests
  # GET /item_requests.json
  def index
    @item_requests = ItemRequest.all
  end

  # GET /item_requests/1
  # GET /item_requests/1.json
  def show
  end

  # GET /item_requests/new
  def new
    @item_request = ItemRequest.new
  end

  # GET /item_requests/1/edit
  def edit
  end

  # POST /item_requests
  # POST /item_requests.json
  def create
    @item_request = ItemRequest.new(item_request_params)

    respond_to do |format|
      if @item_request.save
        format.html { redirect_to @item_request, notice: 'Item request was successfully created.' }
        format.json { render :show, status: :created, location: @item_request }
      else
        format.html { render :new }
        format.json { render json: @item_request.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /item_requests/1
  # PATCH/PUT /item_requests/1.json
  def update
    respond_to do |format|
      if @item_request.update(item_request_params)
        format.html { redirect_to @item_request, notice: 'Item request was successfully updated.' }
        format.json { render :show, status: :ok, location: @item_request }
      else
        format.html { render :edit }
        format.json { render json: @item_request.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /item_requests/1
  # DELETE /item_requests/1.json
  def destroy
    @item_request.destroy
    respond_to do |format|
      format.html { redirect_to item_requests_url, notice: 'Item request was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_item_request
      @item_request = ItemRequest.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def item_request_params
      params.require(:item_request).permit(:item_id, :user_id, :date_request, :estimated_return_date)
    end
end

loanMe/app/helpers/item_requests_helper.rb
module ItemRequestsHelper


  def check_state(item)
     item.state ? 'Item in property' : 'Item loaned'
  end
end

loanMe/app/views/item_requests/_form.html.erb
<%= form_for(@item_request) do |f| %>
  <% if @item_request.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@item_request.errors.count, "error") %> prohibited this item_request from being saved:</h2>

      <ul>
      <% @item_request.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :item_id %><br>
    <%= f.text_field :item_id %>
  </div>
  <div class="field">
    <%= f.label :user_id %><br>
    <%= f.text_field :user_id %>
  </div>
  <div class="field">
    <%= f.label :date_request %><br>
    <%= f.text_field :date_request %>
  </div>
  <div class="field">
    <%= f.label :estimated_return_date %><br>
    <%= f.text_field :estimated_return_date %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

loanMe/app/views/item_requests/edit.html.erb
<h1>Editing Item Request</h1>

<%= render 'form' %>

<%= link_to 'Show', @item_request %> |
<%= link_to 'Back', item_requests_path %>

loanMe/app/views/item_requests/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Item Requests</h1>

<table>
  <thead>
    <tr>
      <th>Item</th>
      <th>User</th>
      <th>Date request</th>
      <th>Estimated return date</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @item_requests.each do |item_request| %>
      <tr>
        <td><%= item_request.item_id %></td>
        <td><%= item_request.user_id %></td>
        <td><%= item_request.date_request %></td>
        <td><%= item_request.estimated_return_date %></td>
        <td><%= link_to 'Show', item_request %></td>
        <td><%= link_to 'Loan', treat_request_path(item_request) %></td>
        <td><%= link_to 'Destroy', item_request, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>


<p>
  <%= link_to 'Back', controller: 'main_window' %>
</p>

loanMe/app/views/item_requests/new.html.erb
<h1>New Item Request</h1>

<%= render 'form' %>

<%= link_to 'Back', item_requests_path %>

loanMe/app/views/item_requests/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Item:</strong>
  <%= @item_request.item_id %>
</p>

<p>
  <strong>User:</strong>
  <%= @item_request.user_id %>
</p>

<p>
  <strong>Date request:</strong>
  <%= @item_request.date_request %>
</p>

<p>
  <strong>Estimated return date:</strong>
  <%= @item_request.estimated_return_date %>
</p>

<%= link_to 'Edit', edit_item_request_path(@item_request) %> |
<%= link_to 'Back', item_requests_path %>